### ISSUE TITLE
Version anglaise ? CGU CGV 

### ISSUE THREAD

**Issue by sinsunsan** [jurismatic/jurismatic#1]
Bravo pour votre travail, et le fait de partager en opensource, est vraiment top. 
Par contre pour certains documents comme les CGU, CGV, on aurait besoin d'une version internationale, donc anglaise. 
Est ce que vous avez l'idée de mettre ca aussi ? 

Je vous ai rajouté à ma page de liens startups 
https://github.com/sinsunsan/archiref_wiki/wiki/Startups-Ressources

**Comment by jurismatic-contrib** [comment]
Merci ! Pour l'instant il n'y a pas de version anglaise prévue mais vous pouvez demander de l'aide à http://11-100-34.com ;)
