### ISSUE TITLE
AG / Dividendes / Rapport de Gestion

### ISSUE THREAD

**Issue by TurhanOz** [jurismatic/jurismatic#3]
Bonjour, 

Merci pour cet intéressant projet :+1: qui sera fort utile pour de nombreux entrepreneurs.

Concernant votre roadmap, avez-vous l'optique d'inclure d'autres modèles de document, tels que 
- modèle de PV d'AG (nomination président, sa rémunération, affectation de résultat (notamment distribution de dividendes...), transfert siège social...)
- modèle de rapport de gestion et d'inventaire
- ...

Merci

**Comment by steeve** [comment]
Pull requests welcome je pense ? :)

**Comment by TurhanOz** [comment]
hehe, les modèles que j'ai en ma possession sont très subjectifs en substance :)

**Comment by jurismatic-contrib** [comment]
N'hésitez pas à contribuer en effet - on va essayer d'updater ça au fur et à mesure !
