### ISSUE TITLE
Certains documents en markdown ne sont pas complets

### ISSUE THREAD

**Issue by steeve** [jurismatic/jurismatic#5]
Par exemple: 
![image](https://cloud.githubusercontent.com/assets/137467/8185940/73ae0866-1447-11e5-9a0a-ea18a68e0ef6.png)

Le `1.` laisse penser qu'ils manque du texte?

**Comment by jurismatic-contrib** [comment]
Nope, c'est plus certainement un problème de conversion word / markedown je pense. Je check :)

**Comment by aloisdg** [comment]
Au passage pourquoi utiliser le format word ?

**Comment by jurismatic-contrib** [comment]
Ca reste le format le plus utilisé chez les cabinets d'avocats, d'ou les deux formats :)
